### ISSUE TITLE
Target attacking/damage not working as expected

### ISSUE THREAD

**Issue by DFreds** [Xacus/demonlord#1]
In order for an actor to roll an attack, the actor must be TARGETING another actor using Foundry's targeting system. This is expected and makes sense (although I'd like it to just roll the d20 plus banes/boons even when a target is not set).

The issue is here. When a hit occurs, the option to roll damage appears. Rolling it gives the option to "Apply Damage to target". However, this does not actually apply the damage to the TARGETED enemy. It applies the damage to the SELECTED TOKEN instead. It would be more useful if actually applied the damage to the target that was attacked.

**Comment by Xacus** [comment]
I could make that optional. If you don't select anyone it just rolls and you as a GM has to tell the outcome.

I actually made it the way you describe in the first version. The problem is that players only have rights to their own actor and can't apply damage to others. I realised that after I made the release. 
Since the GM is the only one that can effect all actors he/she has to micromanage damage/healing. So it's just easier to click on the token/tokens and apply damage this way. If you as a GM attacks a player it could make sense, but then you have two different ways doing damage.

**Comment by DFreds** [comment]
Hm, could you save what the targeted token was when the attack roll was made? Then, yes, I as the DM can click apply the damage and it would just apply to the saved targeted token without me having to do anything. Then you could keep your current targeting rules and everything might be easier.

**Comment by DFreds** [comment]
I believe this might be what MESS is doing (https://github.com/Moerill/mess#universal-features). It works that way, in any case.

**Comment by Zurei** [comment]
Admittedly this threw me off a little bit at the start as well. I don't always have enemy token/sheets fully set up so having it default to still do the roll/calculate damage would be awesome even if it can't apply it.
