### ISSUE TITLE
Problems with Attacks against Monsters

### ISSUE THREAD

**Issue by TheAlaine** [Xacus/demonlord#10]
Hi,

When i attack an monster/creature with an weapon or an spell it will not show the vaule the attack rolls against (defense, agi and str tested).
If i attack an character/player it works like intended.
I tried different token Settings (friendly, neurtal and hostile) but they dont change anything for that.
The extra challenge rolls where you can click the extra button as Gm work on the creatures.

Greetings,

TheAlaine

**Comment by Xacus** [comment]
It's intentional that the players should not see the stats of the creature they attack.

If you goto Game Settings -> Configure Settings -> System Settings and mark "Show enemy stats" then it will always be shown.

Ok, I'll remove it when attacking a character. Apparently I only check if it's a creature.

Challenge rolls is always 10 and not a secret. 

Thanks for bringing this up. I will change it so the GM always can see it.

**Comment by TheAlaine** [comment]
> It's intentional that the players should not see the stats of the creature they attack.
> 
> If you goto Game Settings -> Configure Settings -> System Settings and mark "Show enemy stats" then it will always be shown.
> 
> Ok, I'll remove it when attacking a character. Apparently I only check if it's a creature.
> 
> Challenge rolls is always 10 and not a secret.
> 
> Thanks for bringing this up. I will change it so the GM always can see it.

Ok that makes sense.
That i could not see it as an GM was what made it seem like a bug.

Can you hide the roll on the Challenge Roll and only show the result for the players because as it is now they know the modifiers the creature has.
And show the GM the full roll if that is possible. That should be the most consistent way i think.

**Comment by Xacus** [comment]
In 1.1.5 when a creature is making a challenge roll it only shows the result. You as a GM can see the roll.

**Comment by TheAlaine** [comment]
> In 1.1.5 when a creature is making a challenge roll it only shows the result. You as a GM can see the roll.

Perfect, thank you so much :)
