### ISSUE TITLE
Adding defense options. 

### ISSUE THREAD

**Issue by Avaricious555** [Xacus/demonlord#25]
Hey, love your work. Been using this programme since June this year. Appreciate it all. 

Anyway, for my game of SotDL, we use one of the Forbidden rules where you roll a d20 on all defence rolls and add a modifier for the roll depending on your defence. So your defence modifier is the same as your stat mods. Could you add this as an option sometime down the track?

All the best,

**Comment by Xacus** [comment]
I'm actually not allowed to do that. The only thing outside the core rules I'm allowed to add is Social Combat. And it's only because I asked specifically for permission to do that. I'm not sure people want it? I haven't implemented it yet.

I'm not sure that Forbidden Rules is on Roberts top list if/when the marketplace is coming for Foundry. If paid stuff will be available my guess is that Ancestry, Paths and Spells will be the first ones or an adventure.

**Comment by Avaricious555** [comment]
Oh right, that makes sense then. I guess I will pay for it when it comes haha. Until then, we use our dice IRL. 

I can only say my specific campaign has used social combat once. But I think it would be cool if you did.

Thanks for the reply!  Appreciate ya!
